# Generated by Django 3.2 on 2021-05-07 19:58

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('face_API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='UserFile',
            field=picklefield.fields.PickledObjectField(editable=False, null=True),
        ),
    ]
