# Generated by Django 3.2 on 2021-05-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_API', '0003_alter_customuser_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profilePic',
            field=models.ImageField(upload_to='static/face_API/img/uploads'),
        ),
    ]
